lab06/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tienda/',include('tienda.urls'))
]

tienda/urls.py
from django.urls import path

from . import views

app_name= 'tienda'

urlpatterns = [
    path('',views.index, name='index'),
    path('producto',views.producto,name="producto"),
    path('producto/<int:producto_id>/',views.producto,name="producto"),
    path('categoria/<int:categoria_id>/', views.productos_por_categoria, name='productos_por_categoria'),
]

tienda/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)
    imagen = models.CharField(max_length=200, null=True)
    pub_date = models.DateTimeField('fecha de registro',auto_now=True)
    
    def __str__(self):
        return self.nombre

class Producto(models.Model):
    imagen = models.CharField(max_length=200, null=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=6,decimal_places=2)
    stock = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.nombre

tienda/views.py
from django.shortcuts import render,get_object_or_404 
from .models import Producto, Categoria

# Create your views here.
def index(request):
    product_list = Producto.objects.order_by('nombre')[:6]
    categorias_carrusel = Categoria.objects.order_by('?')[:3]
    categorias = Categoria.objects.all()
    
    context = {
        'product_list': product_list,
        'categorias_carrusel': categorias_carrusel, 
        'categorias': categorias,
    }
    return render(request, 'index.html', context)
def producto(request, producto_id):
    producto = get_object_or_404(Producto, pk=producto_id)
    categorias = Categoria.objects.all()
    context = {
        'producto': producto,
        'categorias': categorias
    }
    return render(request, 'producto.html', context)
def productos_por_categoria(request, categoria_id):
    categoria = get_object_or_404(Categoria, pk=categoria_id)
    productos = Producto.objects.filter(categoria=categoria)
    categorias = Categoria.objects.all()  
    context = {
        'productos': productos,
        'categoria': categoria,
        'categorias': categorias 
    }
    return render(request, 'productos_por_categoria.html', context)

tienda/templates/index.html
{% extends "layout.html" %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for i in categorias_carrusel %}
      <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
    {% endfor %}
  </ol>
  <div class="carousel-inner" role="listbox">
    {% for categoria in categorias_carrusel %}
    <div class="carousel-item {% if forloop.first %}active{% endif %}">
      <img class="d-block img-fluid" src="{{ categoria.imagen }}" alt="Imagen de {{ categoria.nombre }}" width="900" height="350">
    </div>
    {% endfor %}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



<div class="row">
  {% for prod in product_list %}
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <a href="producto/{{ prod.id }}/">

        <img class="card-img-top" src="{{ prod.imagen }}" alt="Imagen de {{ prod.nombre }}">
      </a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="producto/{{ prod.id }}/">{{ prod.nombre }}</a>
        </h4>
        <h5>S/ {{ prod.precio }}</h5>
        <p class="card-text">Categoria: {{ prod.categoria.nombre }}</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

tienda/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shop Homepage</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">    
    <link href="{% static 'css/shop.css' %}" rel="stylesheet">
    <style>
      /* CSS para forzar el footer a estar en la parte inferior */
      html, body {
        height: 100%;
      }

      body {
        display: flex;
        flex-direction: column;
      }

      .container {
        flex: 1;
      }

      footer {
        position: relative;
        bottom: 0;
        width: 100%;
      }
    </style>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'tienda:index' %}">Tienda de Cardenas</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Tienda
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Productos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Categorias</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contacto</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <h1 class="my-4">Categorias</h1>
          <div class="list-group">
            {% for categoria in categorias %}
              <a href="{% url 'tienda:productos_por_categoria' categoria.id %}" class="list-group-item">{{ categoria.nombre }}</a>
            {% endfor %}
          </div>
        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
          <!-- Block Content -->
           {% block content %}{% endblock %}
          <!-- /Block Content -->
        </div>
        <!-- /.col-lg-9 -->
      </div>
      <!-- /.row -->
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

tienda/templates/producto.html
{% extends "layout.html" %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <img src="{{ producto.imagen }}" alt="{{ producto.nombre }}" class="img-fluid">
        </div>
        <div class="col-md-8">
            <h1>{{ producto.nombre }}</h1>
            <p><strong>Categoría:</strong> {{ producto.categoria }}</p>
            <p><strong>Precio:</strong> S/. {{ producto.precio }}</p>
            <p><strong>Stock disponible:</strong> {{ producto.stock }}</p>
            <p><strong>Fecha de publicación:</strong> {{ producto.pub_date|date:"d/m/Y" }}</p>
        </div>
    </div>
</div>
{% endblock %}

tienda/templates/productos_por_categoria.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div class="row">

        <div class="col-lg-9">
            <h2>Productos en la categoría: {{ categoria.nombre }}</h2>
            <div class="row">
                {% for prod in productos %}
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100">
                        <a href="{% url 'tienda:producto' prod.id %}">
                            <img class="card-img-top" src="{{ prod.imagen }}" alt="Imagen de {{ prod.nombre }}">
                        </a>
                        <div class="card-body">
                            <h4 class="card-title">
                                <a href="{% url 'tienda:producto' prod.id %}">{{ prod.nombre }}</a>
                            </h4>
                            <h5>{{ prod.precio }}</h5>
                            <p class="card-text">Categoría: {{ prod.categoria.nombre }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}